'use strict';
const $ = id => document.getElementById(id);
let snapshot;
const dateLabel = date => date ? new Date(`${date}T12:00:00Z`).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'America/New_York'}) : 'Awaiting first edition';
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function sourceLink(source){try{const u=new URL(source.url);if(!['https:','http:'].includes(u.protocol))return null;const a=node('a',source.label||u.hostname);a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';return a;}catch{return null;}}
function percent(v){return Number.isFinite(v)?`${v>0?'+':''}${v.toLocaleString('en-US',{maximumFractionDigits:1})}%`:'Unavailable';}
function card(e){const article=node('article',undefined,'idea');article.id=`rank-${e.rank}`;article.append(node('div',String(e.rank).padStart(2,'0'),'rank'));const body=node('div');const identity=node('div',undefined,'identity');identity.append(node('h3',e.company),node('span',e.ticker,'ticker'),node('span',e.status||'Research needed','status'));body.append(identity);const px=e.price===null||e.price===undefined?'Price unavailable':`${e.currency||''} ${e.price}`;body.append(node('p',`${e.exchange||'Venue unverified'} · ${px}${e.price_as_of?` · as of ${e.price_as_of}`:''}`,'venue'),node('p',`Why new: ${e.why_new}`,'why'),node('p',e.thesis,'thesis'),node('p',`Why this rank: ${e.rank_reason}`,'rank-reason'));
const details=node('details',undefined,'details');details.append(node('summary','Catalyst, risks & sources'));const grid=node('div',undefined,'detail-grid');for(const [title,value] of [['Catalyst',e.catalyst],['Thesis breaker / risk',e.risk],['Upside torque',e.torque],['Evidence confidence',e.confidence]]){const d=node('div');d.append(node('h4',title),node('p',value||'Research needed'));grid.append(d);}details.append(grid);const sources=node('div',undefined,'sources');for(const source of e.sources||[]){const a=sourceLink(source);if(a)sources.append(a);}if(!sources.children.length)sources.append(node('span','Public source link unavailable'));details.append(sources);if(e.gaps?.length)details.append(node('p',`Open questions: ${e.gaps.join(' · ')}`,'gaps'));body.append(details);article.append(body);
const metrics=node('aside',undefined,'metrics');metrics.append(node('h4','Scenario upside'));for(const [title,key] of [['Weighted','weighted_upside_pct'],['Base case','base_upside_pct'],['Bull case','bull_upside_pct'],['Downside','downside_pct']]){const m=node('div',undefined,'metric');const value=e[key];m.append(node('span',title),node('strong',percent(value),Number.isFinite(value)?'':'unknown'));metrics.append(m);}metrics.append(node('p',e.torque||'Torque evidence pending.','torque'));article.append(metrics);return article;}
function render(){const q=$('search').value.trim().toLowerCase();const sort=$('sort').value;const all=snapshot?.equities||[];let rows=all.filter(e=>[e.ticker,e.company,e.thesis,e.why_new].some(v=>String(v||'').toLowerCase().includes(q)));rows.sort((a,b)=>sort==='rank'?a.rank-b.rank:(Number.isFinite(b[sort])?b[sort]:-Infinity)-(Number.isFinite(a[sort])?a[sort]:-Infinity)||a.rank-b.rank);$('ideas').replaceChildren(...rows.map(card));if(!rows.length)$('ideas').append(node('p',q?'No names match your search.':snapshot?.status==='awaiting_digest'?'The first daily edition is being prepared.':'No new names qualified in this edition.','empty'));$('shown').textContent=`${rows.length} of ${all.length} names`;}
async function load(date){try{const path=date?`data/days/${date}.json`:'data/current.json';const response=await fetch(path,{cache:'no-store'});if(!response.ok)throw new Error('Edition unavailable');snapshot=await response.json();$('edition-date').textContent=dateLabel(snapshot.date);$('edition-count').textContent=`${snapshot.equities.length} new names${snapshot.cutoff_at?' · dated research snapshot':''}`;const coverage=$('coverage');coverage.replaceChildren();if(snapshot.status==='awaiting_digest')coverage.append(node('span','No research edition has been published yet.'));else{const cutoff=new Date(snapshot.cutoff_at).toLocaleString('en-US',{timeZone:'America/New_York',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'});const caveats=(snapshot.coverage_gaps||[]);coverage.append(node('span',`Cutoff ${cutoff}. Source ranking is provisional where scenario or peer evidence is incomplete.`));if(caveats.length){const d=node('details');d.append(node('summary',`${caveats.length} coverage notes`));const list=node('ul');caveats.forEach(g=>list.append(node('li',g)));d.append(list);coverage.append(d);}}
const u=new URL(location.href);if(snapshot.date)u.searchParams.set('date',snapshot.date);else u.search='';$('share').href=`https://x.com/intent/tweet?${new URLSearchParams({text:`Daily Stock Delta${snapshot.date?` | ${dateLabel(snapshot.date)}`:''}: new names, short theses, catalysts and risks.`,url:u.href})}`;render();}catch(error){$('ideas').replaceChildren(node('p','This edition could not be loaded. Please refresh or choose another edition.','empty'));$('edition-date').textContent='Edition unavailable';$('edition-count').textContent='';}}
(async()=>{try{const res=await fetch('data/index.json',{cache:'no-store'});if(res.ok){const index=await res.json();for(const d of index.days||[]){const option=node('option',dateLabel(d.date));option.value=d.date;$('day').append(option);}}}catch{}const selected=new URLSearchParams(location.search).get('date');if(selected&&/^\d{4}-\d{2}-\d{2}$/.test(selected)&&[...$('day').options].some(o=>o.value===selected))$('day').value=selected;await load($('day').value);})();
$('day').addEventListener('change',()=>{const u=new URL(location.href);if($('day').value)u.searchParams.set('date',$('day').value);else u.searchParams.delete('date');history.replaceState(null,'',u);load($('day').value);});$('search').addEventListener('input',render);$('sort').addEventListener('change',render);
